name: CI

on: [push, pull_request, workflow_dispatch]

jobs:

    build-and-test:

        runs-on: ubuntu-latest

        steps:

            - uses: actions/checkout@v6
    
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y cmake libmpfi-dev

            - name: Check library versions
              run: dpkg -l | grep -E "pkg-config|cmake|libgmp|libmpfr|libmpfi"

            - name: Configure CMake
              run: cmake -B build -S .

            - name: Build with CMake
              run: cmake --build build

            - name: Run version checker
              run: ./build/check_versions
