name: CI

on: [push, pull_request, workflow_dispatch]

jobs:

    build-and-test:

        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                build_type: [Debug, Release]
            fail-fast: false

        steps:

            - uses: actions/checkout@v6
    
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y cmake libmpfi-dev valgrind

            - name: Check library versions
              run: dpkg -l | grep -E "pkg-config|cmake|libgmp|libmpfr|libmpfi|valgrind"

            - name: Configure CMake (${{ matrix.build_type }})
              run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

            - name: Build with CMake
              run: cmake --build build

            - name: Run version checker
              run: ./build/tests/check_versions

            - name: Run AGM tests
              run: |
                  valgrind --leak-check=full --error-exitcode=1 ./build/tests/check_step
                  valgrind --leak-check=full --error-exitcode=1 ./build/tests/check_nan

            - name: Run AGM examples
              run: valgrind --leak-check=full --error-exitcode=1 ./build/examples/demo_steps
